const ACTIONS = {
    RENDER_MAIN_SCREEN: 'APP:RENDER_MAIN_SCREEN',
    SHOW_ADDITIONAL_SCREEN: 'APP:SHOW_ADDITIONAL_SCREEN',
    HIDE_ADDITIONAL_SCREEN: 'APP:HIDE_ADDITIONAL_SCREEN',
}

export default ACTIONS;
